spring:
  jackson:
    property-naming-strategy: SNAKE_CASE
    default-property-inclusion: non_null
  datasource:
    url: ${JDBC_DATABASE_URL}
    driverClassName: org.postgresql.Driver
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: false
    hbernate:
      ddl-auto: validate
  h2:
    console:
      enabled: false
logging:
  level:
    com.creativeyann17: INFO
jwt:
  secret: ${JWT_SECRET}
  expiration: 300